from enum import IntEnum, auto


class Country(IntEnum):
    """Country Codes (ISO 3166-1 alpha-2)"""

    AD = auto()  # Andorra
    AE = auto()  # United Arab Emirates
    AF = auto()  # Afghanistan
    AG = auto()  # Antigua and Barbuda
    AI = auto()  # Anguilla
    AL = auto()  # Albania
    AM = auto()  # Armenia
    AO = auto()  # Angola
    AQ = auto()  # Antarctica
    AR = auto()  # Argentina
    AS = auto()  # American Samoa
    AT = auto()  # Austria
    AU = auto()  # Australia
    AW = auto()  # Aruba
    AX = auto()  # Åland Islands
    AZ = auto()  # Azerbaijan
    BA = auto()  # Bosnia and Herzegovina
    BB = auto()  # Barbados
    BD = auto()  # Bangladesh
    BE = auto()  # Belgium
    BF = auto()  # Burkina Faso
    BG = auto()  # Bulgaria
    BH = auto()  # Bahrain
    BI = auto()  # Burundi
    BJ = auto()  # Benin
    BL = auto()  # Saint Barthélemy
    BM = auto()  # Bermuda
    BN = auto()  # Brunei Darussalam
    BO = auto()  # Bolivia (Plurinational State of)
    BQ = auto()  # Bonaire, Sint Eustatius and( Saba
    BR = auto()  # Brazil
    BS = auto()  # Bahamas
    BT = auto()  # Bhutan
    BV = auto()  # Bouvet Island
    BW = auto()  # Botswana
    BY = auto()  # Belarus
    BZ = auto()  # Belize
    CA = auto()  # Canada
    CC = auto()  # Cocos (Keeling) Islands
    CD = auto()  # Congo, Democratic Republic of the
    CF = auto()  # Central African Republic
    CG = auto()  # Congo
    CH = auto()  # Switzerland
    CI = auto()  # Côte d'Ivoire
    CK = auto()  # Cook Islands
    CL = auto()  # Chile
    CM = auto()  # Cameroon
    CN = auto()  # China
    CO = auto()  # Colombia
    CR = auto()  # Costa Rica
    CU = auto()  # Cuba
    CV = auto()  # Cabo Verde
    CW = auto()  # Curaçao
    CX = auto()  # Christmas Island
    CY = auto()  # Cyprus
    CZ = auto()  # Czechia
    DE = auto()  # Germany
    DJ = auto()  # Djibouti
    DK = auto()  # Denmark
    DM = auto()  # Dominica
    DO = auto()  # Dominican Republic
    DZ = auto()  # Algeria
    EC = auto()  # Ecuador
    EE = auto()  # Estonia
    EG = auto()  # Egypt
    EH = auto()  # Western Sahara
    ER = auto()  # Eritrea
    ES = auto()  # Spain
    ET = auto()  # Ethiopia
    FI = auto()  # Finland
    FJ = auto()  # Fiji
    FK = auto()  # Falkland Islands (Malvinas)
    FM = auto()  # Micronesia (Federated States of)
    FO = auto()  # Faroe Islands
    FR = auto()  # France
    GA = auto()  # Gabon
    GB = auto()  # United Kingdom of Great Britain and Northern Ireland
    GD = auto()  # Grenada
    GE = auto()  # Georgia
    GF = auto()  # French Guiana
    GG = auto()  # Guernsey
    GH = auto()  # Ghana
    GI = auto()  # Gibraltar
    GL = auto()  # Greenland
    GM = auto()  # Gambia
    GN = auto()  # Guinea
    GP = auto()  # Guadeloupe
    GQ = auto()  # Equatorial Guinea
    GR = auto()  # Greece
    GS = auto()  # South Georgia and the South Sandwich Islands
    GT = auto()  # Guatemala
    GU = auto()  # Guam
    GW = auto()  # Guinea-Bissau
    GY = auto()  # Guyana
    HK = auto()  # Hong Kong
    HM = auto()  # Heard Island and McDonald Islands
    HN = auto()  # Honduras
    HR = auto()  # Croatia
    HT = auto()  # Haiti
    HU = auto()  # Hungary
    ID = auto()  # Indonesia
    IE = auto()  # Ireland
    IL = auto()  # Israel
    IM = auto()  # Isle of Man
    IN = auto()  # India
    IO = auto()  # British Indian Ocean Territory
    IQ = auto()  # Iraq
    IR = auto()  # Iran (Islamic Republic of)
    IS = auto()  # Iceland
    IT = auto()  # Italy
    JE = auto()  # Jersey
    JM = auto()  # Jamaica
    JO = auto()  # Jordan
    JP = auto()  # Japan
    KE = auto()  # Kenya
    KG = auto()  # Kyrgyzstan
    KH = auto()  # Cambodia
    KI = auto()  # Kiribati
    KM = auto()  # Comoros
    KN = auto()  # Saint Kitts and Nevis
    KP = auto()  # Korea (Democratic People's Republic of)
    KR = auto()  # Korea, Republic of
    KW = auto()  # Kuwait
    KY = auto()  # Cayman Islands
    KZ = auto()  # Kazakhstan
    LA = auto()  # Lao People's Democratic Republic
    LB = auto()  # Lebanon
    LC = auto()  # Saint Lucia
    LI = auto()  # Liechtenstein
    LK = auto()  # Sri Lanka
    LR = auto()  # Liberia
    LS = auto()  # Lesotho
    LT = auto()  # Lithuania
    LU = auto()  # Luxembourg
    LV = auto()  # Latvia
    LY = auto()  # Libya
    MA = auto()  # Morocco
    MC = auto()  # Monaco
    MD = auto()  # Moldova, Republic of
    ME = auto()  # Montenegro
    MF = auto()  # Saint Martin (French part)
    MG = auto()  # Madagascar
    MH = auto()  # Marshall Islands
    MK = auto()  # Macedonia, the former Yugoslav Republic of
    ML = auto()  # Mali
    MM = auto()  # Myanmar
    MN = auto()  # Mongolia
    MO = auto()  # Macao
    MP = auto()  # Northern Mariana Islands
    MQ = auto()  # Martinique
    MR = auto()  # Mauritania
    MS = auto()  # Montserrat
    MT = auto()  # Malta
    MU = auto()  # Mauritius
    MV = auto()  # Maldives
    MW = auto()  # Malawi
    MX = auto()  # Mexico
    MY = auto()  # Malaysia
    MZ = auto()  # Mozambique
    NA = auto()  # Namibia
    NC = auto()  # New Caledonia
    NE = auto()  # Niger
    NF = auto()  # Norfolk Island
    NG = auto()  # Nigeria
    NI = auto()  # Nicaragua
    NL = auto()  # Netherlands
    NO = auto()  # Norway
    NP = auto()  # Nepal
    NR = auto()  # Nauru
    NU = auto()  # Niue
    NZ = auto()  # New Zealand
    OM = auto()  # Oman
    PA = auto()  # Panama
    PE = auto()  # Peru
    PF = auto()  # French Polynesia
    PG = auto()  # Papua New Guinea
    PH = auto()  # Philippines
    PK = auto()  # Pakistan
    PL = auto()  # Poland
    PM = auto()  # Saint Pierre and Miquelon
    PN = auto()  # Pitcairn
    PR = auto()  # Puerto Rico
    PS = auto()  # Palestine, State of
    PT = auto()  # Portugal
    PW = auto()  # Palau
    PY = auto()  # Paraguay
    QA = auto()  # Qatar
    RE = auto()  # Réunion
    RO = auto()  # Romania
    RS = auto()  # Serbia
    RU = auto()  # Russian Federation
    RW = auto()  # Rwanda
    SA = auto()  # Saudi Arabia
    SB = auto()  # Solomon Islands
    SC = auto()  # Seychelles
    SD = auto()  # Sudan
    SE = auto()  # Sweden
    SG = auto()  # Singapore
    SH = auto()  # Saint Helena, Ascension and Tristan da Cunha
    SI = auto()  # Slovenia
    SJ = auto()  # Svalbard and Jan Mayen
    SK = auto()  # Slovakia
    SL = auto()  # Sierra Leone
    SM = auto()  # San Marino
    SN = auto()  # Senegal
    SO = auto()  # Somalia
    SR = auto()  # Suriname
    SS = auto()  # South Sudan
    ST = auto()  # Sao Tome and Principe
    SV = auto()  # El Salvador
    SX = auto()  # Sint Maarten (Dutch part)
    SY = auto()  # Syrian Arab Republic
    SZ = auto()  # Eswatini
    TC = auto()  # Turks and Caicos Islands
    TD = auto()  # Chad
    TF = auto()  # French Southern Territories
    TG = auto()  # Togo
    TH = auto()  # Thailand
    TJ = auto()  # Tajikistan
    TK = auto()  # Tokelau
    TL = auto()  # Timor-Leste
    TM = auto()  # Turkmenistan
    TN = auto()  # Tunisia
    TO = auto()  # Tonga
    TR = auto()  # Turkey
    TT = auto()  # Trinidad and Tobago
    TV = auto()  # Tuvalu
    TW = auto()  # Taiwan, Province of China
    TZ = auto()  # Tanzania, United Republic of
    UA = auto()  # Ukraine
    UG = auto()  # Uganda
    UM = auto()  # United States Minor Outlying Islands
    US = auto()  # United States of America
    UY = auto()  # Uruguay
    UZ = auto()  # Uzbekistan
    VA = auto()  # Holy See
    VC = auto()  # Saint Vincent and the Grenadines
    VE = auto()  # Venezuela (Bolivarian Republic of)
    VG = auto()  # Virgin Islands (British)
    VI = auto()  # Virgin Islands
    VN = auto()  # Viet Nam
    VU = auto()  # Vanuatu
    WF = auto()  # Wallis and Futuna
    WS = auto()  # Samoa
    YE = auto()  # Yemen
    YT = auto()  # Mayotte
    ZA = auto()  # South Africa
    ZM = auto()  # Zambia
    ZW = auto()  # Zimbabwe
    
class Continents(IntEnum):
    Africa          = auto()
    Asia            = auto()
    South_America   = auto()
    Europe          = auto()
    Oceania         = auto()
    North_America   = auto()

